### ISSUE TITLE
[Need Help] Update Project Dependencies and Documentation of Project

### ISSUE THREAD

**Issue by yakin18** [yakin18/AI-Chat-Bot#1]
- Update Requirement.txt file
- Update Project README.md file

**Comment by Rohitsingh385** [comment]
hi I would love to work on this can you assign me with this work? you can check my pf I'm pretty good with my work ;)

**Comment by yakin18** [comment]
> hi I would love to work on this can you assign me with this work? you can check my pf I'm pretty good with my work ;)

Yes, Go Ahead

**Comment by Raman84** [comment]
Can i work on this?

**Comment by yakin18** [comment]
Sure, You are good to go.
