### ISSUE TITLE
[Need Help] Please Add Issue Template

### ISSUE THREAD

**Issue by yakin18** [yakin18/AI-Chat-Bot#3]

**Comment by DK-Khambhadiya** [comment]
I would Like to work on this issue, as i have prior knowledge about github templates and all. can you please assign it to me?

**Comment by yakin18** [comment]
Yes, You are ready to go.

**Comment by Rohitsingh385** [comment]
hey I too like to work in this, you can check my profile I'm pretty good with my work can you assign me with this work too?  :)
