### ISSUE TITLE
[Documentation] Beautify README file with description of project 

### ISSUE THREAD

**Issue by yakin18** [yakin18/AI-Chat-Bot#7]
- Add Contribution guidelines
- Beautify README.MD file

**Comment by DK-Khambhadiya** [comment]
Hii @yakin18 , I want to work on this issue.

**Comment by chiragkhatri19** [comment]
Hey can you make a separate graphics related issue, I am a graphics designer and I wanna contribute to your repo by creating a banner for the readme file. So can you please create a new issue and assign that to me. I will make sure it turns out really great

**Comment by chiragkhatri19** [comment]
I wanna make something with a dark and glass look 

Something like this or you can tell if you want any edit in this

<img width="1500" alt="Frame 1Twt Banner (3)" src="https://user-images.githubusercontent.com/89431059/193462278-72554cdb-a3b6-42c2-80d3-269563199a1c.png">
